add_newline = false

[directory]
format = "[$path](underline #f57800)[$read_only]($read_only_style) "
truncation_length = 3
home_symbol = "~"
read_only_style = "bold red"

[character]
success_symbol = "[➜ ](bold green)"
error_symbol = "[✗ ](bold red)"

[username]
format = "[$user](bold blue)[ @ ](red)"
disabled = false
show_always = true

[git_branch]
symbol = "git "

[cmd_duration]
min_time = 100
format = " [took](bold yellow) [$duration](bold green)"

[aws]
symbol = "aws "

[conda]
symbol = "conda "

[crystal]
symbol = "crystal "

[cmake]
symbol = "cmake "

[dart]
symbol = "dart "

[deno]
symbol = "deno "

[dotnet]
symbol = ".NET "


[docker_context]
symbol = "docker "

[elixir]
symbol = "elixir "

[elm]
symbol = "elm "

[golang]
symbol = "go "

[hg_branch]
symbol = "hg "

[java]
symbol = "java "

[julia]
symbol = "julia "

[kotlin]
symbol = "kotlin "

[nodejs]
symbol = "nodejs "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix_shell "

[ocaml]
symbol = "ocaml "

[package]
disabled = false
symbol = "package "

[perl]
symbol = "perl "

[php]
symbol = "php "

[purescript]
symbol = "purescript "

[python]
symbol = "python "
python_binary = "python3"

[ruby]
symbol = "ruby "

[rust]
symbol = "rust "

[scala]
symbol = "scala "

[swift]
symbol = "swift "
